create table tb_sales (id int8 generated by default as identity, amount float8, date date, deals int4, visited int4, seller_id int8, primary key (id));
create table tb_sellers (id int8 generated by default as identity, name varchar(255), primary key (id));
alter table if exists tb_sales add constraint FKp0nn0oixeiw2fq3jivj6vnsu foreign key (seller_id) references tb_sellers;


postgres://
hzghkxyzfehvck:
e23b747e6196214e3282e78f01a75c5f9aefbb90f4d9ebd93b9b2ef75f15733f

@
ec2-54-224-120-186.compute-1.amazonaws.com
:
5432
/
d3qtqfs3tpi3cq